Use area without lines or points for areweesmifiedyet chart, and also show total in tooltip
mozilla-spidermonkey/mozilla-spidermonkey.github.io pull request #115
Opened 2022-10-03 08:04 UTC by arai-a

* Remove lines and points from the chart, to make it clearer it's stacked chart
 * Show total number in the tooltip when hover over the chart

2022-10-07 12:29 UTC, codehag requested changes
Overall I support the change, but I think the colors will be hard to see, and have a suggestion on how to change them.

2022-10-07 12:29 UTC, codehag commented on areweesmifiedyet/css/page.css
> +  opacity: 0.4 !important;
I think we want to use different contrasts for these two. Currently, the contrast is 1:1.8, and while this isn't text -- it makes the line a little hard to distinguish. 

<img width="709" alt="Screenshot 2022-10-07 at 14 10 19" src="https://user-images.githubusercontent.com/26968615/194551042-e216d40d-1826-4746-94d7-49b24223a097.png">

I would propose pushing to contrast to 1:5, or something like this:

<img width="898" alt="Screenshot 2022-10-07 at 14 09 14" src="https://user-images.githubusercontent.com/26968615/194551092-d35e71d0-36c2-409f-a111-402216a02bf1.png">

To get this, we would set the c3-area-esmCount opacity ot something like 0.4, or we would return the c3-line-esmCount to having an opacity of 1. 

(by the way, In case you are curious about the effect: the reason it is hard to see the line with the current contrast is because our ability to distinguish position is colorblind. If two things are too close in terms of contrast, they will appear to "move". This is a really nice video explaining how they eye can position things https://youtu.be/fwPqSxR-Z5E?t=1510 -- from 25:10 to 26:52)

2022-10-07 12:57 UTC, arai-a commented on areweesmifiedyet/css/page.css
> +  opacity: 0.4 !important;
Thank you for the feedback.
Unfortunately I cannot simply set the opacity to 1, because the vertical line which appears when you hover the graph is under the area, and setting the opacity to 1 makes the vertical line hidden.
I'll try tweaking the graph, or look for other way to get the same color with semi-transparent area

2022-10-07 16:10 UTC, codehag commented on areweesmifiedyet/css/page.css
> +  opacity: 0.4 !important;
Ok, I will approve this so you don't need to wait on me (since my day is finishing). We can always follow up after

2022-10-07 16:10 UTC, codehag approved these changes
Approving modulo colour contrast fix

2022-10-18 06:03 UTC, arai-a commented
I managed to make the line in front of the graph and now `opacity: 1` can be used, but still having hard time choosing the colors.

Is the contrast "1:5" correct?  it's hard to achieve it with the current orange+blue color scheme.
either the orange becomes too bright or the blue become too dark, or both.
(maybe I'm misunderstanding how to get the contrast ratio with expected color?)

<img width="812" alt="graph" src="https://user-images.githubusercontent.com/6299746/196347249-5758231d-6a4b-47dd-806a-a1e9578b61b3.png">

I wonder if it's better taking different approach.
perhaps add a border line to both area with same color?

2022-10-18 06:11 UTC, arai-a commented
Here's graph with border line
<img width="801" alt="graph2" src="https://user-images.githubusercontent.com/6299746/196349507-af238946-70ff-469b-9672-1166f05b773f.png">

2022-10-18 11:02 UTC, codehag commented
Both are looking better. I agree that the orange may be too light. We don't have to hit 5:1 exactly, we just need to line to be well defined and easy to see. But, this still limits what can be done.

If it works with the border line, that might be best. So I support that approach.

2022-10-18 11:08 UTC, arai-a commented
thanks!  I'll go with border line

2022-10-19 16:16 UTC, merged