Pull Last Updated info from GitHub to accurately reflect last update
mozilla-spidermonkey/mozilla-spidermonkey.github.io pull request #132
Opened 2023-06-08 21:17 UTC by mgaudet

The previous use of site.time would lie because it would only use the time Jekyll ran

2023-06-08 22:39 UTC, hotsphink requested changes

2023-06-08 22:39 UTC, hotsphink commented on tech_tree/index.md
> +  .then((response) => { return response.json(); })
Your aesthetic choices do not match mine and therefore are wrong. `.then(response => response.json())` is prettier.

(Yes, you may ignore this comment, as I am confident in the absolute superiority of my aesthetics and am not insecure enough to need others to adopt them to maintain my self-esteem.)

2023-06-08 22:39 UTC, hotsphink commented on tech_tree/index.md
> +      document.getElementById("lastUpdated").innerHTML =  d.toLocaleDateString() + " (" + d.toLocaleTimeString() + ")"
`s/innerHTML/innerText/` please. I'm sure there is no locale where `toLocaleDateString` will produce `<iframe src="https://` or whatever, but `.innerHTML` is scary and should not be used lightly.

And if you want nitpicks, then fix the double space and `s/var/const/` or (`let` if you are anti-`const`). But I don't really care about those.

2023-06-09 20:38 UTC, mgaudet commented on tech_tree/index.md
> +  .then((response) => { return response.json(); })
:) Fixed.

2023-06-09 20:38 UTC, mgaudet commented on tech_tree/index.md
> +      document.getElementById("lastUpdated").innerHTML =  d.toLocaleDateString() + " (" + d.toLocaleTimeString() + ")"
Fixed :)

2023-06-09 21:33 UTC, hotsphink approved these changes

2023-06-09 21:47 UTC, merged